# Generated by Django 3.2.5 on 2021-07-03 11:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('cvc', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('expiry_month', models.PositiveSmallIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
