# Generated by Django 3.2.5 on 2021-07-07 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_purchased_credit_card'),
        ('user', '0002_alter_creditcard_cvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')]),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
