# Generated by Django 3.2.5 on 2021-07-15 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_card', '0002_creditcard_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='purchased_credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_card.creditcard'),
        ),
        migrations.AddField(
            model_name='order',
            name='selections',
            field=models.ManyToManyField(to='order.Selection'),
        ),
    ]
