# Generated by Django 3.2.5 on 2021-07-07 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0001_initial'),
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchased_credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_card.creditcard'),
        ),
    ]
