# Generated by Django 3.2.5 on 2021-07-08 05:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
