name: test

on: [push]

jobs:
    main:
        name: Main
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: postgres
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout the source code
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2.2.2
              with:
                  python-version: 3.9.5
            - name: Install required packages
              run: |
                  pip install --upgrade pip
                  pip install coverage codecov
                  pip install -r requirements.txt
            - name: Test and generate coverage report
              run: |
                  coverage run manage.py test -v 3
                  coverage xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  files: ./coverage.xml
                  env_vars: OS,PYTHON
                  name: codecov-pangpangeats
                  fail_ci_if_error: true
                  verbose: true
            - name: Github Checks
              uses: LouisBrunner/checks-action@v1.1.1
              if: always()
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  name: Django Test
                  conclusion: ${{ job.status }}
